/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_api_v1_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{code}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sections */
        get: operations["list_sections_api_v1_courses__code__sections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Plan */
        post: operations["validate_plan_api_v1_plans_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/auto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auto Plan */
        post: operations["auto_plan_api_v1_plans_auto_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_api_v1_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_v1_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_v1_plans__plan_id__get"];
        put?: never;
        post?: never;
        /** Delete Plan */
        delete: operations["delete_plan_api_v1_plans__plan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explain Plan */
        get: operations["explain_plan_api_v1_plans__plan_id__explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chat Sessions */
        get: operations["list_chat_sessions_api_v1_chat_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chat Messages */
        get: operations["list_chat_messages_api_v1_chat_sessions__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_students_me_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/me/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcript */
        get: operations["get_transcript_api_v1_students_me_transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/me/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Transcript */
        post: operations["import_transcript_api_v1_students_me_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AutoPlanRequest
         * @example {
         *       "exclude": [],
         *       "must_include": [],
         *       "term": "1/2569"
         *     }
         */
        AutoPlanRequest: {
            /**
             * Term
             * @description ภาคการศึกษารูปแบบ "ภาค/ปีพ.ศ."
             * @example 1/2569
             */
            term: string;
            preferences?: components["schemas"]["StudentPreferences"] | null;
            /** Must Include */
            must_include?: string[];
            /** Exclude */
            exclude?: string[];
        };
        /** AutoPlanResponse */
        AutoPlanResponse: {
            /** Plans */
            plans: components["schemas"]["GeneratedPlan"][];
        };
        /** Body_import_transcript_api_v1_students_me_import_post */
        Body_import_transcript_api_v1_students_me_import_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Id */
            id: number;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            status: components["schemas"]["MessageStatus"];
            /** Sources */
            sources?: components["schemas"]["SourceItem"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChatMessageListResponse */
        ChatMessageListResponse: {
            /** Items */
            items: components["schemas"]["ChatMessage"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * ChatRequest
         * @example {
         *       "message": "ช่วยวางแผนลงทะเบียนเทอมหน้า อยากว่างวันศุกร์"
         *     }
         */
        ChatRequest: {
            /** Session Id */
            session_id?: number | null;
            /** Message */
            message: string;
            /** Plan Draft */
            plan_draft?: Record<string, never> | null;
        };
        /** ChatSessionListResponse */
        ChatSessionListResponse: {
            /** Items */
            items: components["schemas"]["ChatSessionSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ChatSessionSummary */
        ChatSessionSummary: {
            /** Id */
            id: number;
            /** Title */
            title?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ConflictItem
         * @description ต้องตรงกับ RESPONSE CONTRACT ของ 06 — 02 ไม่ตัดสินเอง
         */
        ConflictItem: {
            /** Type */
            type: string;
            /** Message */
            message: string;
            /** Section Ids */
            section_ids?: string[];
            /** Details */
            details?: Record<string, never>;
        };
        /**
         * Course
         * @example {
         *       "code": "CPE301",
         *       "credits": 3,
         *       "name_en": "Data Structures and Algorithms",
         *       "name_th": "โครงสร้างข้อมูลและขั้นตอนวิธี",
         *       "prerequisites": [
         *         "CPE201"
         *       ]
         *     }
         */
        Course: {
            /** Code */
            code: string;
            /** Name Th */
            name_th: string;
            /** Name En */
            name_en: string;
            /** Credits */
            credits: number;
            /** Prerequisites */
            prerequisites?: string[];
        };
        /** CourseListResponse */
        CourseListResponse: {
            /** Items */
            items: components["schemas"]["Course"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * Day
         * @enum {string}
         */
        Day: "MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT" | "SUN";
        /** ExplainResponse */
        ExplainResponse: {
            /** Explanation */
            explanation: string;
            /** Sources */
            sources?: components["schemas"]["SourceItem"][];
        };
        /**
         * FeedbackRequest
         * @example {
         *       "rating": 5,
         *       "reason": "แผนไม่ชนกันเลย",
         *       "target_id": "12",
         *       "target_type": "plan"
         *     }
         */
        FeedbackRequest: {
            /**
             * Target Type
             * @enum {string}
             */
            target_type: "plan" | "chat_message" | "explanation";
            /** Target Id */
            target_id: string;
            /** Rating */
            rating: number;
            /** Reason */
            reason?: string | null;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Feedback Id */
            feedback_id: number;
        };
        /** GeneratedPlan */
        GeneratedPlan: {
            /** Sections */
            sections: string[];
            /** Total Credits */
            total_credits: number;
            /** Relaxed Constraints */
            relaxed_constraints?: string[];
            /** Explanation */
            explanation?: string | null;
            /** Warnings */
            warnings?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResult */
        ImportResult: {
            /** Imported Courses */
            imported_courses: number;
            /** Retake Required */
            retake_required?: string[];
            /** Credits Remaining */
            credits_remaining: number;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * LoginRequest
         * @example {
         *       "password": "admin1234",
         *       "username": "admin"
         *     }
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @example {
         *       "role": "student",
         *       "student_id": "6500000000",
         *       "username": "admin"
         *     }
         */
        LoginResponse: {
            /** Username */
            username: string;
            /** Student Id */
            student_id: string;
            /** Role */
            role: string;
        };
        /**
         * MeResponse
         * @example {
         *       "role": "student",
         *       "student_id": "6500000000",
         *       "username": "admin"
         *     }
         */
        MeResponse: {
            /** Username */
            username: string;
            /** Student Id */
            student_id: string;
            /** Role */
            role: string;
        };
        /**
         * MeetingSlot
         * @example {
         *       "day": "MON",
         *       "end": "11:50",
         *       "room": "ENG-301",
         *       "start": "09:00"
         *     }
         */
        MeetingSlot: {
            day: components["schemas"]["Day"];
            /**
             * Start
             * @description เวลารูปแบบ "HH:MM"
             * @example 09:00
             */
            start: string;
            /**
             * End
             * @description เวลารูปแบบ "HH:MM"
             * @example 09:00
             */
            end: string;
            /** Room */
            room?: string | null;
        };
        /**
         * MessageStatus
         * @enum {string}
         */
        MessageStatus: "complete" | "interrupted" | "cancelled";
        /** Meta */
        Meta: {
            /** Request Id */
            request_id: string;
            /** Took Ms */
            took_ms: number;
        };
        /**
         * PlanCreateRequest
         * @example {
         *       "name": "แผนหลัก",
         *       "section_ids": [
         *         "CPE301-01",
         *         "CPE302-02"
         *       ],
         *       "term": "1/2569"
         *     }
         */
        PlanCreateRequest: {
            /**
             * Term
             * @description ภาคการศึกษารูปแบบ "ภาค/ปีพ.ศ."
             * @example 1/2569
             */
            term: string;
            /** Name */
            name: string;
            /** Section Ids */
            section_ids: string[];
        };
        /** PlanCreateResponse */
        PlanCreateResponse: {
            /** Plan Id */
            plan_id: number;
        };
        /** PlanDetail */
        PlanDetail: {
            /** Id */
            id: number;
            /**
             * Term
             * @description ภาคการศึกษารูปแบบ "ภาค/ปีพ.ศ."
             * @example 1/2569
             */
            term: string;
            /** Name */
            name: string;
            /** Sections */
            sections: components["schemas"]["Section"][];
            last_validation?: components["schemas"]["PlanValidateResponse"] | null;
        };
        /** PlanListResponse */
        PlanListResponse: {
            /** Items */
            items: components["schemas"]["PlanSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** PlanSummary */
        PlanSummary: {
            /** Id */
            id: number;
            /**
             * Term
             * @description ภาคการศึกษารูปแบบ "ภาค/ปีพ.ศ."
             * @example 1/2569
             */
            term: string;
            /** Name */
            name: string;
            /** Total Credits */
            total_credits: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PlanValidateRequest
         * @example {
         *       "section_ids": [
         *         "CPE301-01",
         *         "CPE302-02"
         *       ],
         *       "term": "1/2569"
         *     }
         */
        PlanValidateRequest: {
            /**
             * Term
             * @description ภาคการศึกษารูปแบบ "ภาค/ปีพ.ศ."
             * @example 1/2569
             */
            term: string;
            /** Section Ids */
            section_ids: string[];
        };
        /** PlanValidateResponse */
        PlanValidateResponse: {
            /** Conflicts */
            conflicts?: components["schemas"]["ConflictItem"][];
            /** Warnings */
            warnings?: components["schemas"]["WarningItem"][];
            summary: components["schemas"]["ValidateSummary"];
        };
        /**
         * Section
         * @example {
         *       "course_code": "CPE301",
         *       "course_name_th": "โครงสร้างข้อมูลและขั้นตอนวิธี",
         *       "credits": 3,
         *       "exam": {
         *         "day": "SAT",
         *         "end": "11:00",
         *         "start": "09:00"
         *       },
         *       "meetings": [
         *         {
         *           "day": "MON",
         *           "end": "11:50",
         *           "room": "ENG-301",
         *           "start": "09:00"
         *         }
         *       ],
         *       "seats_available": 5,
         *       "seats_total": 40,
         *       "section_id": "CPE301-01",
         *       "teacher": "อ.สมชาย ใจดี"
         *     }
         */
        Section: {
            /** Section Id */
            section_id: string;
            /** Course Code */
            course_code: string;
            /** Course Name Th */
            course_name_th: string;
            /** Teacher */
            teacher: string;
            /** Credits */
            credits: number;
            /** Seats Available */
            seats_available: number;
            /** Seats Total */
            seats_total: number;
            /** Meetings */
            meetings: components["schemas"]["MeetingSlot"][];
            exam?: components["schemas"]["MeetingSlot"] | null;
        };
        /** SectionListResponse */
        SectionListResponse: {
            /** Items */
            items: components["schemas"]["Section"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * SourceItem
         * @example {
         *       "document_id": "doc-regulation-2566",
         *       "page": 12,
         *       "section": "ข้อ 18",
         *       "title": "ข้อบังคับฯ"
         *     }
         */
        SourceItem: {
            /** Title */
            title: string;
            /** Section */
            section: string;
            /** Page */
            page?: number | null;
            /** Document Id */
            document_id: string;
            /** Url */
            url?: string | null;
        };
        /** StudentPreferences */
        StudentPreferences: {
            /** Free Days */
            free_days?: components["schemas"]["Day"][];
            /**
             * No Early Class
             * @default false
             */
            no_early_class: boolean;
            /** Max Credits */
            max_credits?: number | null;
        };
        /** StudentProfile */
        StudentProfile: {
            /** Student Id */
            student_id: string;
            /** Program Id */
            program_id: string;
            /** Program Name */
            program_name: string;
            /** Year Level */
            year_level: number;
            /** Gpax */
            gpax: number;
            /** Credits Earned */
            credits_earned: number;
            /** Credits Remaining */
            credits_remaining: number;
        };
        /** SuccessEnvelope[AutoPlanResponse] */
        SuccessEnvelope_AutoPlanResponse_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["AutoPlanResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[ChatMessageListResponse] */
        SuccessEnvelope_ChatMessageListResponse_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["ChatMessageListResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[ChatSessionListResponse] */
        SuccessEnvelope_ChatSessionListResponse_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["ChatSessionListResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[CourseListResponse] */
        SuccessEnvelope_CourseListResponse_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["CourseListResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[ExplainResponse] */
        SuccessEnvelope_ExplainResponse_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["ExplainResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[FeedbackResponse] */
        SuccessEnvelope_FeedbackResponse_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["FeedbackResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[ImportResult] */
        SuccessEnvelope_ImportResult_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["ImportResult"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[LoginResponse] */
        SuccessEnvelope_LoginResponse_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["LoginResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[MeResponse] */
        SuccessEnvelope_MeResponse_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["MeResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[PlanCreateResponse] */
        SuccessEnvelope_PlanCreateResponse_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["PlanCreateResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[PlanDetail] */
        SuccessEnvelope_PlanDetail_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["PlanDetail"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[PlanListResponse] */
        SuccessEnvelope_PlanListResponse_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["PlanListResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[PlanValidateResponse] */
        SuccessEnvelope_PlanValidateResponse_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["PlanValidateResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[SectionListResponse] */
        SuccessEnvelope_SectionListResponse_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["SectionListResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[StudentProfile] */
        SuccessEnvelope_StudentProfile_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["StudentProfile"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[TranscriptResponse] */
        SuccessEnvelope_TranscriptResponse_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            data: components["schemas"]["TranscriptResponse"];
            meta: components["schemas"]["Meta"];
        };
        /** SuccessEnvelope[dict] */
        SuccessEnvelope_dict_: {
            /**
             * Ok
             * @constant
             * @enum {boolean}
             */
            ok: true;
            /** Data */
            data: Record<string, never>;
            meta: components["schemas"]["Meta"];
        };
        /** TranscriptCourse */
        TranscriptCourse: {
            /** Course Code */
            course_code: string;
            /** Course Name Th */
            course_name_th: string;
            /** Credits */
            credits: number;
            /** Grade */
            grade: string;
            /**
             * Term
             * @description ภาคการศึกษารูปแบบ "ภาค/ปีพ.ศ."
             * @example 1/2569
             */
            term: string;
        };
        /** TranscriptResponse */
        TranscriptResponse: {
            /** Courses */
            courses: components["schemas"]["TranscriptCourse"][];
            /** Credits By Category */
            credits_by_category: {
                [key: string]: number;
            };
        };
        /** ValidateSummary */
        ValidateSummary: {
            /** Total Credits */
            total_credits: number;
            /** Section Count */
            section_count: number;
            /** Is Valid */
            is_valid: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WarningItem */
        WarningItem: {
            /** Type */
            type: string;
            /** Message */
            message: string;
            /** Details */
            details?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_LoginResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_MeResponse_"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_dict_"];
                };
            };
        };
    };
    list_courses_api_v1_courses_get: {
        parameters: {
            query?: {
                q?: string | null;
                term?: string | null;
                day?: components["schemas"]["Day"] | null;
                teacher?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_CourseListResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sections_api_v1_courses__code__sections_get: {
        parameters: {
            query: {
                term: string;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_SectionListResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_plan_api_v1_plans_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_PlanValidateResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auto_plan_api_v1_plans_auto_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_AutoPlanResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_v1_plans_get: {
        parameters: {
            query?: {
                term?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_PlanListResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_v1_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_PlanCreateResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_v1_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_PlanDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_plan_api_v1_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_plan_api_v1_plans__plan_id__explain_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_ExplainResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chat_sessions_api_v1_chat_sessions_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_ChatSessionListResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chat_messages_api_v1_chat_sessions__session_id__messages_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_ChatMessageListResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_students_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_StudentProfile_"];
                };
            };
        };
    };
    get_transcript_api_v1_students_me_transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_TranscriptResponse_"];
                };
            };
        };
    };
    import_transcript_api_v1_students_me_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_transcript_api_v1_students_me_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_ImportResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_FeedbackResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
